-- Seeder for Services, Templates and Service Promotions with randomized dates
SET FOREIGN_KEY_CHECKS = 0;

-- Truncate tables before seeding
TRUNCATE TABLE services;
TRUNCATE TABLE templates;
TRUNCATE TABLE service_promotions;

-- Insert Services
INSERT INTO services (code, name, price, unit, category, features, url, description, type, is_active, created_at, updated_at) VALUES 
('INET-HOME-10', 'Internet Home 10Mbps', 250000.00, 'Monthly', 'Access Home', '["Kecepatan hingga 10Mbps","Kuota unlimited","Cocok untuk browsing dan media sosial","Stabil untuk belajar dan kerja ringan dari rumah","Dukungan teknis responsif"]', 'https://kawan-nusa.com/service/home-10', 'Paket internet rumah dengan kecepatan hingga 10Mbps yang dirancang untuk kebutuhan harian seperti browsing, media sosial, streaming ringan, video call, dan aktivitas belajar dari rumah. Layanan ini cocok untuk pengguna personal atau keluarga kecil yang membutuhkan koneksi internet stabil, praktis, dan terjangkau untuk penggunaan sehari-hari.', 'Internet', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('INET-HOME-30', 'Internet Home 30Mbps', 450000.00, 'Monthly', 'Access Home', '["Kecepatan hingga 30Mbps","Kuota unlimited","Mendukung banyak perangkat sekaligus","Cocok untuk streaming HD dan meeting online","Koneksi stabil untuk kebutuhan keluarga"]', 'https://kawan-nusa.com/service/home-30', 'Paket internet rumah 30Mbps yang ideal untuk keluarga modern dengan kebutuhan koneksi yang lebih aktif. Layanan ini mendukung penggunaan beberapa perangkat secara bersamaan untuk streaming, meeting online, belajar daring, bermain game ringan, dan aktivitas digital lainnya dengan performa yang tetap lancar dan stabil sepanjang hari.', 'Internet', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('INET-HOME-50', 'Internet Home 50Mbps', 650000.00, 'Monthly', 'Access Home', '["Kecepatan hingga 50Mbps","Kuota unlimited","Cocok untuk streaming 4K","Optimal untuk gaming dan upload konten","Stabil untuk rumah dengan banyak pengguna"]', 'https://kawan-nusa.com/service/home-50', 'Paket internet rumah berkecepatan tinggi hingga 50Mbps yang cocok untuk kebutuhan digital intensif. Sangat ideal untuk streaming video 4K, gaming online, upload dan download file berukuran besar, hingga penggunaan banyak perangkat secara bersamaan dalam satu rumah. Layanan ini dirancang untuk memberikan pengalaman internet yang cepat, nyaman, dan lebih maksimal.', 'Internet', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('INET-BIZ-50', 'Internet Business 50Mbps', 1500000.00, 'Monthly', 'Access Business', '["Kecepatan dedicated 50Mbps","SLA hingga 99.9%","Cocok untuk operasional bisnis menengah","Koneksi stabil untuk aplikasi kantor","Dukungan teknis untuk kebutuhan usaha"]', 'https://kawan-nusa.com/service/biz-50', 'Layanan internet bisnis 50Mbps yang dirancang untuk mendukung kebutuhan operasional perusahaan skala kecil hingga menengah. Koneksi yang stabil dan andal sangat cocok digunakan untuk email bisnis, cloud application, meeting online, akses sistem internal, hingga aktivitas operasional kantor yang membutuhkan kualitas jaringan yang konsisten dan profesional.', 'Internet', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('INET-BIZ-100', 'Internet Business 100Mbps', 2800000.00, 'Monthly', 'Access Business', '["Kecepatan dedicated 100Mbps","SLA hingga 99.9%","Cocok untuk kantor besar dan korporasi","Mendukung traffic data tinggi","Performa optimal untuk layanan bisnis kritikal"]', 'https://kawan-nusa.com/service/biz-100', 'Solusi internet bisnis dengan bandwidth besar hingga 100Mbps yang dirancang untuk perusahaan dengan kebutuhan konektivitas tinggi. Cocok untuk kantor besar, perusahaan dengan banyak pengguna aktif, pemakaian cloud service, video conference intensif, pertukaran data besar, dan kebutuhan operasional bisnis yang menuntut performa jaringan cepat, stabil, dan berkelanjutan.', 'Internet', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('HOST-UNL', 'Unlimited Web Hosting', 500000.00, 'Yearly', 'Digital Business', '["Storage unlimited","Gratis domain .com","Cocok untuk website perusahaan","Mendukung kebutuhan hosting bisnis","Pengelolaan website lebih praktis"]', 'https://kawan-nusa.com/service/hosting-unl', 'Layanan web hosting tahunan dengan kapasitas penyimpanan tanpa batas yang dirancang untuk mendukung website perusahaan, profil bisnis, landing page promosi, maupun kebutuhan website profesional lainnya. Dilengkapi dengan domain gratis .com dan kemudahan pengelolaan, layanan ini cocok עבור bisnis yang ingin membangun kehadiran digital yang lebih kuat dan terpercaya.', 'Web Hosting', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('VPS-BASIC', 'Cloud VPS Basic', 150000.00, 'Monthly', 'Digital Business', '["1 Core CPU","RAM 2GB","SSD 40GB","Cocok untuk aplikasi skala kecil","Fleksibel untuk development dan testing"]', 'https://kawan-nusa.com/service/vps-basic', 'Cloud VPS Basic adalah server virtual yang cocok untuk kebutuhan aplikasi skala kecil, website, development environment, dan testing system. Dengan spesifikasi 1 core CPU, RAM 2GB, dan SSD 40GB, layanan ini memberikan fleksibilitas yang cukup untuk pengguna yang membutuhkan infrastruktur digital yang efisien, terjangkau, dan mudah dikembangkan sesuai kebutuhan.', 'Data Cloud', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('VPN-SECURE', 'Corporate VPN', 1000000.00, 'Monthly', 'Digital Business', '["Mendukung hingga 50 user","Enkripsi AES-256","Akses aman dari mana saja","Cocok untuk kerja remote","Perlindungan koneksi untuk data perusahaan"]', 'https://kawan-nusa.com/service/vpn-secure', 'Layanan Corporate VPN yang dirancang untuk memberikan akses jaringan perusahaan secara aman dari berbagai lokasi. Dengan dukungan hingga 50 pengguna dan enkripsi AES-256, layanan ini cocok untuk kebutuhan kerja remote, akses sistem internal perusahaan, serta perlindungan data penting agar tetap aman selama proses komunikasi dan pertukaran informasi berlangsung.', 'Jasa', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW()),

('COLO-1U', 'Colocation Server 1U', 2500000.00, 'Monthly', 'Digital Business', '["Ruang rack 1U","Daya listrik hingga 400W","Bandwidth 100Mbps","Keamanan data center terjamin","Cocok untuk penitipan server perusahaan"]', 'https://kawan-nusa.com/service/colo-1u', 'Layanan colocation server 1U untuk perusahaan yang ingin menempatkan servernya di data center yang aman dan andal. Dengan dukungan ruang rack 1U, daya hingga 400W, dan bandwidth 100Mbps, layanan ini sangat cocok untuk kebutuhan hosting server bisnis, aplikasi internal, maupun infrastruktur TI perusahaan yang membutuhkan keamanan fisik, stabilitas koneksi, dan lingkungan operasional profesional.', 'Data Cloud', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 50000) MINUTE), NOW());
-- Insert Templates
INSERT INTO templates (name, thumbnail, description, png, jpg, mp4, psd, is_active, created_at, updated_at) VALUES 
('Laporan Bisnis Modern', 'uploads/templates/thumbnails/business_pro.jpg', 'Template presentasi profesional untuk kebutuhan bisnis dan korporat dengan desain yang bersih dan modern.', 'uploads/templates/assets/business_pro.png', 'uploads/templates/assets/business_pro.jpg', NULL, 'uploads/templates/assets/business_pro.psd', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 100000) MINUTE), NOW()),
('Portal Berita Minimalis', 'uploads/templates/thumbnails/news_minimalist.jpg', 'Desain portal berita yang bersih, responsif, dan fokus pada kenyamanan membaca artikel.', 'uploads/templates/assets/news_minimalist.png', 'uploads/templates/assets/news_minimalist.jpg', NULL, NULL, 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 100000) MINUTE), NOW()),
('Intro Video Kreatif Agency', 'uploads/templates/thumbnails/video_intro.jpg', 'Template video intro dengan animasi dinamis untuk meningkatkan branding konten digital Anda.', NULL, NULL, 'uploads/templates/assets/video_intro.mp4', NULL, 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 100000) MINUTE), NOW()),
('Banner Promo Instagram', 'uploads/templates/thumbnails/ig_promo.jpg', 'Template desain banner promosi untuk feed Instagram yang eye-catching.', 'uploads/templates/assets/ig_promo.png', 'uploads/templates/assets/ig_promo.jpg', NULL, 'uploads/templates/assets/ig_promo.psd', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 100000) MINUTE), NOW()),
('Company Profile Simple', 'uploads/templates/thumbnails/com_pro.jpg', 'Template company profile satu halaman yang elegan dan informatif.', 'uploads/templates/assets/com_pro.png', 'uploads/templates/assets/com_pro.jpg', NULL, NULL, 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 100000) MINUTE), NOW()),
('Logo Kit Minimalis', 'uploads/templates/thumbnails/logo_kit.jpg', 'Paket template logo minimalis yang mudah dimodifikasi sesuai brand Anda.', 'uploads/templates/assets/logo_kit.png', NULL, NULL, 'uploads/templates/assets/logo_kit.psd', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 100000) MINUTE), NOW());

-- Insert Service Promotions
INSERT INTO service_promotions (service_code, title, description, image, url, start_period, end_period, is_active, created_at, updated_at) VALUES 
('INET-HOME-10', 'Diskon Instalasi Home', 'Bayar lebih hemat dengan gratis biaya instalasi untuk paket Home 10Mbps.', 'uploads/promotions/home_promo.jpg', 'https://kawan-nusa.com/promo/home-install', '2026-03-01', '2026-03-31', 1, DATE_ADD('2026-02-01 00:00:00', INTERVAL FLOOR(RAND() * 10000) MINUTE), NOW()),
('INET-BIZ-50', 'Double Speed Business', 'Dapatkan kecepatan 100Mbps dengan harga 50Mbps selama 3 bulan pertama.', 'uploads/promotions/biz_double.jpg', 'https://kawan-nusa.com/promo/biz-double', '2026-04-01', '2026-04-30', 1, DATE_ADD('2026-03-01 00:00:00', INTERVAL FLOOR(RAND() * 10000) MINUTE), NOW()),
('HOST-UNL', 'Migrasi Gratis', 'Pindahkan website Anda ke server kami secara gratis tanpa downtime.', 'uploads/promotions/hosting_migration.jpg', 'https://kawan-nusa.com/promo/hosting-migration', '2026-01-01', '2026-12-31', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 10000) MINUTE), NOW()),
('VPN-SECURE', 'Free Trial 30 Hari', 'Coba layanan VPN korporat kami selama 30 hari tanpa biaya sepeser pun.', 'uploads/promotions/vpn_trial.jpg', 'https://kawan-nusa.com/promo/vpn-trial', '2026-05-01', '2026-05-31', 1, DATE_ADD('2026-04-01 00:00:00', INTERVAL FLOOR(RAND() * 10000) MINUTE), NOW()),
(NULL, 'Cashback 100% Saldo', 'Spesial untuk pendaftar bulan ini! Dapatkan cashback saldo 100% untuk top-up pertama kali.', 'uploads/promotions/new_user_cashback.jpg', 'https://kawan-nusa.com/promo/new-user', '2026-01-01', '2026-12-31', 1, DATE_ADD('2026-01-01 00:00:00', INTERVAL FLOOR(RAND() * 10000) MINUTE), NOW());

SET FOREIGN_KEY_CHECKS = 1;
