export enum CustomerType {
    EDUCATION_SCHOOL_UNIVERSITY = "Education / School / University",
    HOTEL = "Hotel",
    GOVERNMENT = "Government",
    MEDICATION_PHARMACY = "Medication & Pharmacy",
    WARNET = "Warnet",
    TRAVEL = "Travel",
    IT_TELECOMMUNICATION = "IT & Telecommunication",
    OTHERS = "Others",
    INSURANCE = "Insurance",
    AGRICULTURE_PLANTATION = "Agriculture / Plantation",
    AUTOMOTIVE = "Automotive",
    EKSPEDISI_EXPORT_IMPORT_TRANSPORTATION = "Ekspedisi / Export Import / Transportation",
    FINANCE_BANKING_SECURITY = "Finance / Banking / Security",
    PROPERTY = "Property",
    MOBILE_PREPAID_CREDIT = "Mobile Prepaid Credit",
    HOME_USER = "Home User",
    SMALL_OFFICE = "Small Office",
    CAFE_RESTAURANT = "Cafe / Restaurant",
    RUMAH_SAKIT = "Rumah Sakit",
    JASA_KONSTRUKSI = "Jasa Konstruksi",
    WHOLESALE_SUPPLIER_RETAIL = "Wholesale / Supplier / Retail",
    PABRIK_MANUFACTURING = "Pabrik / Manufactoring",
    ENERGY_UTILITY = "Energy / Utility",
    HOTEL_RESORT = "Hotel / Resort",
    RUMAH_IBADAH = "Rumah Ibadah",
    SPORT_VENUE = "Sport Venue"
}
